/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;


import DTOs.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;

//import <default package>

/**
 *
 * @author Andres
 */
public class ABMTipoImpuesto77 extends javax.swing.JFrame {

    /**
     * Creates new form ABMTipoImpuesto
     */
    private ControladorABMTipoImpuesto controlador = new ControladorABMTipoImpuesto();
    public ABMTipoImpuesto77() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstTipoImpuesto = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnNuevoTipoImpuesto = new javax.swing.JButton();
        btnModificarTipoImpuesto = new javax.swing.JButton();
        btnEliminarTipoImpuesto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lstTipoImpuesto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTipoImpuesto.setName(""); // NOI18N
        jScrollPane1.setViewportView(lstTipoImpuesto);

        jLabel1.setText("Tipos de Impuesto");

        btnNuevoTipoImpuesto.setText("Nuevo");
        btnNuevoTipoImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoTipoImpuestoActionPerformed(evt);
            }
        });

        btnModificarTipoImpuesto.setText("Modificar");
        btnModificarTipoImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarTipoImpuestoActionPerformed(evt);
            }
        });

        btnEliminarTipoImpuesto.setText("Eliminar");
        btnEliminarTipoImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTipoImpuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNuevoTipoImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificarTipoImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btnEliminarTipoImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(118, 118, 118))
                    .addComponent(jLabel1))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnNuevoTipoImpuesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarTipoImpuesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarTipoImpuesto)
                        .addGap(0, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start(){
        //lstAtributoExcluido.setModel(new DefaultListModel());
        //lstAtributoExcluido.setEnabled(false);
        //lstAtributoSeleccionado.setModel(new DefaultListModel());
        //lstAtributoSeleccionado.setEnabled(false);
        //btnOrdenSubir.setEnabled(false);
        //btnOrdenBajar.setEnabled(false);
        //btnAgregar.setEnabled(false);
        //btnQuitar.setEnabled(false);
        //btnGuardar.setEnabled(false);
        
        lstTipoImpuesto.setEnabled(true);
        //txtNombreTipoImpuesto.setEnabled(true);
        //chkImporteEditable.setEnabled(true);
        btnNuevoTipoImpuesto.setEnabled(true);
        btnModificarTipoImpuesto.setEnabled(true);
        btnEliminarTipoImpuesto.setEnabled(true);
        
        //lblCodigo.setText("Codigo:");
        //txtNombreTipoImpuesto.setText("");
        //chkImporteEditable.setSelected(false);
        
        List<DTOTipoImpuesto> listaTI;
        listaTI = controlador.buscarTipoImpuesto();
        
        DefaultListModel listModelTI = new DefaultListModel();
        
        for(DTOTipoImpuesto dtoTI: listaTI){
            int codigo = dtoTI.getCodigo();
            String nombre = dtoTI.getNombre();
            boolean editable = dtoTI.isImporteEditable();
            String elem = (editable ? "+" : "-") + "(" + codigo + ") " + nombre;
            listModelTI.addElement(elem);
        }
        
        lstTipoImpuesto.setModel(listModelTI);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        start();
    }//GEN-LAST:event_formWindowOpened

    private void btnNuevoTipoImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoTipoImpuestoActionPerformed
        
        ABMTipoImpuesto78 img78 =new ABMTipoImpuesto78();
        img78.setVisible(true);
        

        //String nombreTI = txtNombreTipoImpuesto.getText();
       // boolean editable = chkImporteEditable.isSelected();
        
        List<DTOAtributo> listaAtrib;
        //listaAtrib = controlador.crearTipoImpuesto(nombreTI, editable);//crea en nuevo tipo impuesto q le envio y lo asigna a la variable listaAtrib
        //listaAtrib.get(0).
        DefaultListModel listModelExcAtrib = new DefaultListModel();//crea dos listas de tipo defaultlistmodel
        DefaultListModel listModelSelAtrib = new DefaultListModel();// "
        
       // for(DTOAtributo atrib: listaAtrib){//  varia el primer objeto de la lista
         //   int codigoAtr = atrib.getCodigo();
           // String nombreAtr = atrib.getNombre();
          //  String tipoAtr = atrib.getTipo();
            //String elem = "(" + codigoAtr + ") " + nombreAtr + " | " + tipoAtr;
            //listModelExcAtrib.addElement(elem);
        //}
        
        //lstAtributoExcluido.setEnabled(true);
        //lstAtributoExcluido.setModel(listModelExcAtrib);
        
        //lstAtributoSeleccionado.setEnabled(true);
        //lstAtributoSeleccionado.setModel(listModelSelAtrib);
        
        //btnOrdenSubir.setEnabled(true);
        //btnOrdenBajar.setEnabled(true);
        //btnAgregar.setEnabled(true);
        //btnQuitar.setEnabled(true);
        //btnGuardar.setEnabled(true);
        
        lstTipoImpuesto.setEnabled(true);
        //txtNombreTipoImpuesto.setEnabled(false);
        //chkImporteEditable.setEnabled(false);
        btnNuevoTipoImpuesto.setEnabled(false);
        btnModificarTipoImpuesto.setEnabled(false);
        btnEliminarTipoImpuesto.setEnabled(false);
    }//GEN-LAST:event_btnNuevoTipoImpuestoActionPerformed

    private void btnModificarTipoImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarTipoImpuestoActionPerformed
        ABMTipoImpuestoModificar img79 =new ABMTipoImpuestoModificar();
        img79.setVisible(true);
        
        String elem = lstTipoImpuesto.getSelectedValue();
        String delims = "[ )(]+";
        String[] tokens = elem.split(delims);
        
        boolean editable = false;
        if("+".equals(tokens[0])) editable = true;
       // chkImporteEditable.setSelected(editable);
        ABMTipoImpuestoModificar.chkImporteEditable.setSelected(editable);
        //Integer codigoTI = Integer.parseInt(tokens[1]);
        //lblCodigo.setText("Codigo: " + codigoTI.toString());
        //ABMTipoImpuestoModificar.lblCodigo.setText(parseInt(tokens[1]);
        ABMTipoImpuestoModificar.lblCodigo.setText(tokens[1]);
        //txtNombreTipoImpuesto.setText(tokens[2]);//es un vector token q lleva nos ayuda desglosar lo q va en la pantalla
        ABMTipoImpuestoModificar.txtNombreTipoImpuesto.setText(tokens[2]);
        
        
        /*List<DTOTipoImpAtrib> listaDTOTIA = controlador.modificarTipoImpuesto(codigoTI);
        
        DefaultListModel listModelExcAtrib = new DefaultListModel();
        DefaultListModel listModelSelAtrib = new DefaultListModel();
        
        for(DTOTipoImpAtrib dtoTIA:listaDTOTIA){
            DTOAtributo atr = dtoTIA.getDtoAtributo();
            int codigoAtr = atr.getCodigo();
            String nombreAtr = atr.getNombre();
            String tipoAtr = atr.getTipo();
            
            String elemAtr = "("+codigoAtr+") "+nombreAtr+" | "+tipoAtr;
            
            int orden = dtoTIA.getOrden();
            if(orden == -1){
                listModelExcAtrib.addElement(elemAtr);
            }
            else{
                if(orden == listModelSelAtrib.size()){
                    listModelSelAtrib.addElement(elemAtr);
                }
                else if(orden < listModelSelAtrib.size()){
                    listModelSelAtrib.setElementAt(elemAtr, orden);
                }
                else{
                    for(int i = listModelSelAtrib.size(); i < orden; i++){
                        String nulo = "";
                        listModelSelAtrib.addElement(nulo);
                    }
                    listModelSelAtrib.add(orden, elemAtr);
                }
            }
        }*/
        
       // lstAtributoExcluido.setEnabled(true);
        //lstAtributoExcluido.setModel(listModelExcAtrib);
        
        //lstAtributoSeleccionado.setEnabled(true);
        //lstAtributoSeleccionado.setModel(listModelSelAtrib);
        
        //btnOrdenSubir.setEnabled(true);
        //btnOrdenBajar.setEnabled(true);
        //btnAgregar.setEnabled(true);
        //btnQuitar.setEnabled(true);
        //btnGuardar.setEnabled(true);
        
        /*lstTipoImpuesto.setEnabled(true);
        btnNuevoTipoImpuesto.setEnabled(false);
        btnModificarTipoImpuesto.setEnabled(false);
        btnEliminarTipoImpuesto.setEnabled(false);*/
    }//GEN-LAST:event_btnModificarTipoImpuestoActionPerformed

    private void btnEliminarTipoImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTipoImpuestoActionPerformed
        String elem = lstTipoImpuesto.getSelectedValue();
        String delims = "[ )(]+";
        String[] tokens = elem.split(delims);
        int codigo = Integer.parseInt(tokens[1]);
        
        controlador.eliminarTipoImpuesto(codigo);
        
        start();
    }//GEN-LAST:event_btnEliminarTipoImpuestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMTipoImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMTipoImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMTipoImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMTipoImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMTipoImpuesto77().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarTipoImpuesto;
    private javax.swing.JButton btnModificarTipoImpuesto;
    private javax.swing.JButton btnNuevoTipoImpuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstTipoImpuesto;
    // End of variables declaration//GEN-END:variables
}
